#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================
ynh_script_progression --message="Recreating the dedicated system user..." --weight=2

ynh_system_user_create --username=$app --home_dir="$install_dir"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..."

ynh_restore_file --origin_path="$install_dir"

# Restore permissions on app files
chown -R $app:www-data "$install_dir"
chmod 750 "$install_dir"

#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================

ynh_restore_file --origin_path="/etc/php/${phpversion}/fpm/pool.d/$app.conf"

#=================================================
# RESTORE CUSTOM SCRIPTS AND SERVICES
#=================================================
ynh_restore_file --origin_path="/usr/local/bin/facture-fdn.sh"
ynh_restore_file --origin_path="/etc/systemd/system/attestation-facture-fdn.service"
ynh_restore_file --origin_path="/etc/systemd/system/attestation-facture-fdn.timer"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression --message="Reloading NGINX web server and PHP-FPM..."

ynh_systemd_action --service_name=php${phpversion}-fpm --action=reload
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last

