#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=2

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=2

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

#=================================================
# CUSTOM FILES THAT CAN BE UPGRADED (ignore subfolders)
#=================================================

# Don't copy default templates for upgrade (users
# have probably configured their own by now)
cp ../www/index.php "$install_dir/www/"
cp ../www/bulma.min.css "$install_dir/www/"
cp ../www/lib.typ "$install_dir/www/"

#=================================================
# CUSTOM SCRIPTS AND SERVICES
#=================================================
cp ../helpers/facture-fdn.sh /usr/local/bin/facture-fdn.sh
ynh_add_config --template="attestation-facture-fdn.service" --destination="/etc/systemd/system/attestation-facture-fdn.service"
ynh_add_config --template="attestation-gc.service" --destination="/etc/systemd/system/attestation-gc.service"
cp ../helpers/attestation-facture-fdn.timer /etc/systemd/system/
cp ../helpers/attestation-gc.timer /etc/systemd/system/
systemctl daemon-reload

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown -R $app:www-data "$install_dir"
chmod 750 "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last

